config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/authentication'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks, only: [:index, :show, :create, :edit, :new, :destroy] do
    resources :comments, only: [:create]
  end
  post "tasks/:id/completed" => "tasks#completed"
  post "tasks/:id/incomplete" => "tasks#incomplete"

  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
  validates :content, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :is_done, inclusion: { in: [true, false] }
    has_many :comments, dependent: :destroy
    belongs_to :assignee, class_name: 'User', optional: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :tasks, dependent: :destroy, foreign_key: 'user_id'
  has_many :assigned_tasks, class_name: 'Task', foreign_key: 'assignee_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @comment = @task.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @task, notice: 'コメントを追加しました。'
    else
      render 'tasks/show'
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def authentication
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, 
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @done_tasks = Task.where(is_done: true)
    @undone_tasks = Task.where(is_done: false)
    @user = current_user
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comments = @task.comments
    @comment = Comment.new
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    @task.email = current_user.email
    @task.user_id = current_user.id
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def completed
    @task = Task.find(params[:id])
    @task.is_done = true
    @task.save
    if @task.save
      redirect_to @task, notice: '完了にしました'
    else
      render :index
    end
  end

  def incomplete
    @task = Task.find(params[:id])
    @task.is_done = false
    @task.save
    if @task.save
      redirect_to @task, notice: '完了にしました'
    else
      render :index
    end
  end

  def authentication
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :is_done, :duedate, :assignee_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/authentication.html.erb
<h1>Home#authentication</h1>
<p>Find me in app/views/home/authentication.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :is_done %>
    <%= form.check_box :is_done %>
  </div>

  <div class="field">
    <%= form.label :duedate %>
    <%= form.date_field :duedate %>
  </div>

  <div class="field">
    <%= form.label :assignee_id, '担当者' %>
    <%= form.collection_select(:assignee_id, User.all, :id, :email, { include_blank: true }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @user.email %>がログイン中</h2>
<h1>Tasks</h1>

<table>
<h3>未完了</h3>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>説明</th>
      <th>完了フラグ</th>
      <th>作成日</th>
      <th>更新日</th>
      <th>作成者</th>
      <th>期限</th>
      <th>担当者</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @undone_tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.is_done %></td>
        <td><%= task.created_at %></td>
        <td><%= task.updated_at %></td>
        <td><%= task.email %></td>
        <td><%= task.duedate %></td>
        <td><%= task.assignee.email if task.assignee %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to '完了にする',"/tasks/#{task.id}/completed",id: task.id,method: :post %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<table>
<h3>完了</h3>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>説明</th>
      <th>完了フラグ</th>
      <th>作成日</th>
      <th>更新日</th>
      <th>作成者</th>
      <th>期限</th>
      <th>担当者</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @done_tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.is_done %></td>
        <td><%= task.created_at %></td>
        <td><%= task.updated_at %></td>
        <td><%= task.email %></td>
        <td><%= task.duedate %></td>
        <td><%= task.assignee.email if task.assignee %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to '未完了にする',"/tasks/#{task.id}/incomplete",id: task.id,method: :post %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Is done:</strong>
  <%= @task.is_done %>
</p>

<p>
  <strong>期日:</strong>
  <%= @task.duedate %>
</p>

<p>
  <strong>担当者:</strong>
  <%= @task.assignee.email if @task.assignee %>
</p>

<h2>コメント一覧</h2>
<% @comments.each do |c| %>
  <div>
    <a href="/users/<%= @task.user_id %>"><%= c.user.email %></a>
    <%= c.content %>
    <hr>
  </div>
<% end %>

<%= form_with(model: [task, comment], local: true) do |form| %>
  <div class="field">
    <%= form.text_field :content, placeholder: 'コメントを入力...', required: true %>
  </div>

  <div class="actions">
    <%= form.submit '送信' %>
  </div>
<% end %>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>